import { StyleSheet } from 'react-native';
import colors from './colors.js';

const buttonStyles = StyleSheet.create({
    defaultButton: {
        backgroundColor: colors.secondary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        elevation: 2,
    },
    primaryButton: {
        backgroundColor: colors.secondary, // Changed from primary to secondary
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        elevation: 2,
    },
    secondaryButton: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.secondary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
    },
    outlineButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
    },
    ghostButton: {
        backgroundColor: 'transparent',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
    },
    iconButton: {
        backgroundColor: 'transparent',
        padding: 8,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    chip: {
        backgroundColor: colors.secondary,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 15,
        paddingVertical: 5,
        paddingHorizontal: 12,
        marginRight: 5,
        marginBottom: 5,
    },
    closeButton: {
        backgroundColor: colors.ghosted,
        padding: 5,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    disabled: {
        backgroundColor: colors.ghosted,
        borderColor: colors.ghosted,
        opacity: 0.6,
    },
    fullWidth: {
        width: '100%',
    },
    small: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        minHeight: 32,
        borderRadius: 5,
    },
    large: {
        paddingVertical: 18,
        paddingHorizontal: 28,
        minHeight: 56,
        borderRadius: 8,
    },
    shadow: {
        shadowColor: colors.Shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    button: {
        backgroundColor: '#007bff',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 4,
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
export default buttonStyles;